---
version: '3.6'
services:
  mysql:
    platform: linux/arm64/v8
    image: mysql:8
    ports:
      - "14407:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
